services:
  senju:
    build:
      context: .
      target: dev
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - .:/app
    depends_on:
      - ollama
  
  ollama:
    image: docker.io/ollama/ollama   
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0


